# Generated by Django 5.1.6 on 2025-03-14 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_message_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='comments',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main_page.message'),
        ),
    ]
