# Generated by Django 5.1.6 on 2025-03-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_remove_message_comments_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_comment',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H/')),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('forum_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main_page.forumuser')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='main_page.post')),
            ],
        ),
    ]
