# Generated by Django 5.1.6 on 2025-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_remove_post_forum_user_remove_message_forum_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='messages',
            field=models.ManyToManyField(related_name='tags', to='main_page.post'),
        ),
    ]
