# Generated by Django 5.1.6 on 2025-03-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_tag_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='messages',
            new_name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
