# Generated by Django 5.1.6 on 2025-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_rename_messages_tag_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
