# Generated by Django 5.1.5 on 2025-05-05 12:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_comment_description_alter_post_title_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment'), ('user', 'post')},
        ),
    ]
